# Generated by Django 2.2.6 on 2019-10-24 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.IntegerField(choices=[(1, 'aliyun'), (2, 'tencent')], default=1)),
                ('service', models.IntegerField(choices=[(1, 'sms')], default=1)),
                ('options', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'service-type',
                'verbose_name_plural': 'service-type',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('app_key', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='services.ServiceType')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'service',
            },
        ),
    ]
