# Generated by Django 2.2.7 on 2019-11-11 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', django_extensions.db.fields.RandomCharField(blank=True, db_index=True, editable=False, include_alpha=False, length=6, lowercase=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('expired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_code', to='services.Service')),
            ],
            options={
                'verbose_name': 'sms-verify-code',
                'verbose_name_plural': 'sms-verify-code',
                'unique_together': {('service', 'code')},
            },
        ),
    ]
